[package]
name = "mqtt"
version = "0.1.0"
authors = ["Arnav Singh <arsing@microsoft.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
log = "0.4"
tokio-codec = "0.2.0-alpha.6"

[dev-dependencies]
env_logger = "0.6"
structopt = "0.2"
structopt-derive = "0.2"
tokio = "0.2.0-alpha.6"
